In [14]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\Churn_Modelling - Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [7]:
lb = LabelEncoder()

In [10]:
df['Surname'] = lb.fit_transform(df['Surname'])
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [11]:
x = df.drop(columns = ['Exited'])
y = df['Exited']

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [15]:
np.round(x_train.describe(),2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5012.51,15690665.10,1502.17,651.65,0.75,0.55,38.90,5.00,76102.14,1.53,0.70,0.51,100431.29
std,2887.65,71847.43,847.15,96.37,0.83,0.50,10.52,2.88,62461.01,0.58,0.46,0.50,57518.92
min,2.00,15565701.00,0.00,350.00,0.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,90.07
25%,2512.75,15628215.50,765.00,585.00,0.00,0.00,32.00,3.00,0.00,1.00,0.00,0.00,51364.12
50%,5014.50,15690738.00,1525.00,653.00,1.00,1.00,37.00,5.00,96447.52,1.00,1.00,1.00,100487.72
75%,7505.25,15753164.25,2236.00,719.00,1.00,1.00,44.00,7.00,127611.33,2.00,1.00,1.00,149595.84
max,10000.00,15815660.00,2930.00,850.00,2.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [18]:
x_train_sc = sc.fit_transform(x_train)

In [19]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [20]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-1.74,-1.77,-3.13,-0.91,-1.09,-1.99,-1.74,-1.22,-0.92,-1.54,-1.03,-1.74
25%,-0.87,-0.87,-0.87,-0.69,-0.91,-1.09,-0.66,-0.70,-1.22,-0.92,-1.54,-1.03,-0.85
50%,0.00,0.00,0.03,0.01,0.30,0.91,-0.18,-0.00,0.33,-0.92,0.65,0.97,0.00
75%,0.86,0.87,0.87,0.70,0.30,0.91,0.49,0.69,0.82,0.81,0.65,0.97,0.85
max,1.73,1.74,1.69,2.06,1.51,0.91,5.05,1.73,2.80,4.26,0.65,0.97,1.73

In [23]:
x_train_new.to_csv("train_data.csv", index=False)
x_train_new.to_excel("train_data.xlsx", index=False)