In [ ]:
# Normalization: MinMaxscaler 
#Data ko ek fixed range (usually 0 se 1) me scale karta hai.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\toyota - toyota.csv')
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,GT86,2016,16000,Manual,24089,Petrol,265,36.2,2.0
1,GT86,2017,15995,Manual,18615,Petrol,145,36.2,2.0
2,GT86,2015,13998,Manual,27469,Petrol,265,36.2,2.0
3,GT86,2017,18998,Manual,14736,Petrol,150,36.2,2.0
4,GT86,2017,17498,Manual,36284,Petrol,145,36.2,2.0
...,...,...,...,...,...,...,...,...,...
6733,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0
6734,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3
6735,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4
6736,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3
6737,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3

In [4]:
df = df.drop(columns = ['model','transmission','fuelType'])

In [5]:
df

      year  price  mileage  tax   mpg  engineSize
0     2016  16000    24089  265  36.2         2.0
1     2017  15995    18615  145  36.2         2.0
2     2015  13998    27469  265  36.2         2.0
3     2017  18998    14736  150  36.2         2.0
4     2017  17498    36284  145  36.2         2.0
...    ...    ...      ...  ...   ...         ...
6733  2011   5500    30000   20  58.9         1.0
6734  2011   4985    36154  125  50.4         1.3
6735  2012   4995    46000  125  57.6         1.4
6736  2011   3995    60700  125  50.4         1.3
6737  2011   4495    45128  125  50.4         1.3

[6738 rows x 6 columns]

In [9]:
x = df.drop(columns ='engineSize')
y = df['engineSize']

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
mn = MinMaxScaler()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [11]:
x_train_new = mn.fit_transform(x_train)

In [13]:
x_train_new_df = pd.DataFrame(x_train_new, columns=x_train.columns)
x_train_new_df.describe().round(2)

          year    price  mileage      tax      mpg
count  5390.00  5390.00  5390.00  5390.00  5390.00
mean      0.85     0.20     0.13     0.17     0.26
std       0.10     0.11     0.11     0.13     0.07
min       0.00     0.00     0.00     0.00     0.00
25%       0.82     0.13     0.05     0.00     0.23
50%       0.86     0.17     0.11     0.24     0.26
75%       0.91     0.24     0.18     0.26     0.29
max       1.00     1.00     1.00     1.00     1.00