In [ ]:
# You have to  apply column transformer on these 2 datasets . 
# And calculate total shape  using column transformer and without using column transformer .

In [1]:
import numpy as np
import pandas as pd

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\credit_scoring - credit_scoring.csv')

In [3]:
df.head(3)

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771,6,957000,2.76,12,Auto Loan

In [4]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [40]:
cat_cols = df.select_dtypes(include = 'object').columns
Num_cols = df.select_dtypes(exclude = 'object').columns

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_39780\427803985.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include = 'object').columns

In [41]:
df_dummies = pd.get_dummies(df,columns = cat_cols)
df_dummies.shape

(1000, 22)

In [47]:
ct = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'),
         cat_cols)
    ],
    remainder='passthrough'
)

In [48]:
X_transformed = ct.fit_transform(df)

print("Shape with ColumnTransformer:", X_transformed.shape)

Shape with ColumnTransformer: (1000, 22)

In [36]:
cat_cols

     Gender Marital Status Education Level Employment Status   Type of Loan
0      Male        Married          Master          Employed  Personal Loan
1      Male        Married     High School        Unemployed      Auto Loan
2    Female         Single          Master          Employed      Auto Loan
3    Female        Married             PhD        Unemployed      Auto Loan
4      Male        Married        Bachelor     Self-Employed  Personal Loan
..      ...            ...             ...               ...            ...
995    Male       Divorced     High School          Employed      Auto Loan
996    Male       Divorced        Bachelor        Unemployed      Home Loan
997  Female         Single          Master     Self-Employed  Personal Loan
998  Female        Married             PhD     Self-Employed      Auto Loan
999  Female        Married          Master     Self-Employed      Auto Loan

[1000 rows x 5 columns]

In [64]:
df2new = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\insurance - insurance.csv')

In [66]:
cat_col_new = df2.select_dtypes(include='object').columns
cat_col_new

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_39780\1152076594.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col_new = df2.select_dtypes(include='object').columns

Index(['sex', 'smoker', 'region'], dtype='str')

In [56]:
df2.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [57]:
df2.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [62]:
print(df2.columns.tolist())
print(cat_col2)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']
Index(['Gender', 'Marital Status', 'Education Level', 'Employment Status',
       'Type of Loan'],
      dtype='str')

In [68]:
# df_get_dummm = pd.get_dummies(df2,columns = cat_col2)
df_dummies2 = pd.get_dummies(df2,columns = cat_col_new)
df_dummies2

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False,False,True,False,False
1334,18,31.920,0,2205.98080,True,False,True,False,True,False,False,False
1335,18,36.850,0,1629.83350,True,False,True,False,False,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False,False,False,False,True
1337,61,29.070,0,29141.36030,True,False,False,True,False,True,False,False

In [69]:
df_dummies2.shape

(1338, 12)

In [73]:
from sklearn.compose  import ColumnTransformer

In [78]:
ct = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(handle_unknown='ignore'), cat_col_new)
    ],
    remainder='passthrough'
)

X_transformed = ct.fit_transform(df2)

print("Shape after ColumnTransformer:", X_transformed.shape)

Shape after ColumnTransformer: (1338, 12)