In [1]:
# Decision Tree

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\insurance - insurance.csv')

In [4]:
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [9]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [13]:
x = df.drop(columns = 'charges')
y  = df['charges']

In [14]:
cat  = x.select_dtypes(include = 'object')

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_17800\2675790427.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat  = x.select_dtypes(include = 'object')

In [17]:
lb = LabelEncoder()

In [18]:
for i in cat:
    x[i] = lb.fit_transform(x[i])

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state = 42)

In [22]:
from sklearn.tree import DecisionTreeRegressor

In [23]:
dt = DecisionTreeRegressor()

In [24]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [25]:
y_pred = dt.predict(x_test)

In [27]:
from sklearn.metrics import r2_score

In [29]:
r2_score(y_test,y_pred)

0.7163354956664136

In [30]:
df2 = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\covid_toy - covid_toy.csv')

In [31]:
df2.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [33]:
df2.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [35]:
df2['fever'] = df2['fever'].fillna(df2['fever'].mean())

In [36]:
x = df2.drop(columns = 'has_covid')
y = df2['has_covid']

In [39]:
cat = df2.select_dtypes(include = 'object').columns

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_17800\3238301885.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat = df2.select_dtypes(include = 'object').columns

In [41]:
x

    age  gender  fever  cough  city
0    60       1  103.0      0     2
1    27       1  100.0      0     1
2    42       1  101.0      0     1
3    31       0   98.0      0     2
4    65       0  101.0      0     3
..  ...     ...    ...    ...   ...
95   12       0  104.0      0     0
96   51       0  101.0      1     2
97   20       0  101.0      0     0
98    5       0   98.0      1     3
99   10       0   98.0      1     2

[100 rows x 5 columns]

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [48]:
dtc = DecisionTreeClassifier()

In [49]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [52]:
y_pred = dtc.predict(x_test)

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
accuracy_score(y_test,y_pred)

0.4