
Employee attrition analysis is a type of
behavioural analysis where we study the
behaviour and characteristics of the employees
who left the organization and compare their
characteristics with the current employees to
find the employees who may leave the organization soon.

A high rate of attrition of employees can be expensive for any company in terms of recruitment and
training costs, loss of productivity and morale reduction of employees. By identifying the causes of
attrition, a company can take measures to reduce the attrition of employees and maintain precious
employees.

In [63]:
import pandas as pd
import numpy as np
import seaborn as sns

1. Separate categorical columns and Numerical columns . When you have separate categorical data then you have to replace its sub-categories to numbers i.e. has_covid[yes,no] ---> has_covid[0,1] . 
2. Check if there are missing values are or not ? If there are then handle missing values . 
3. You have to rename 3 column names of Numerical columns . 
4. You have to filter 15-25 rows with all columns of Categorical  columns . 
5. You have to check statically view of Nummerical columns . 
6. You have to export categorical data into csv format and Nummerical data into excel format . 
7. In your Numerical data , you have to arrange data in ascending order using a single column .

In [111]:
df = pd.read_csv(r'C:\Users\PIYUSH\Downloads\Datasets\Attrition - Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [112]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [113]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (6.8.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from plotly) (2.22.1)
Requirement already satisfied: packaging in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [114]:
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "plotly_white"

In [115]:
attr_df = df[df['Attrition'] == 'Yes']

In [116]:
attr_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [121]:
attr_by_dept = attr_df.groupby(['Department']).size().reset_index(name='Count').sort_values(by='Count', ascending=False)
attr_by_dept

               Department  Count
1  Research & Development    133
2                   Sales     92
0         Human Resources     12

In [123]:
attr_by_ed = attr_df.groupby(['EducationField']).size().reset_index(name='Count').sort_values(by='Count', ascending=False)
attr_by_ed

     EducationField  Count
1     Life Sciences     89
3           Medical     63
2         Marketing     35
5  Technical Degree     32
4             Other     11
0   Human Resources      7

In [128]:
attr_by_yr = attr_df.groupby(['YearsSinceLastPromotion']).size().reset_index(name='Count').sort_values(by='Count', ascending=False)
attr_by_yr

    YearsSinceLastPromotion  Count
0                         0    110
1                         1     49
2                         2     27
7                         7     16
3                         3      9
6                         6      6
4                         4      5
8                         9      4
13                       15      3
5                         5      2
11                       13      2
10                       11      2
9                        10      1
12                       14      1

In [136]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [129]:
# Create a donut chart
fig = go.Figure(data=[go.Pie(
labels=attr_by_yr['YearsSinceLastPromotion'],
values=attr_by_yr['Count'],
hole=0.4,
marker=dict(colors=['red', 'green']),
textposition='inside'

)])

# Update the Layout
fig.update_layout(title='Attrition by Years Since Last Promotion')

# Show the chart
fig.show()

In [ ]:
attr_by_yr = attr_df.groupby(['YearsSince']).size().reset_index(name='Count').sort_values(by='Count', ascending=False)
attr_by_yr

In [118]:
# Create a donut chart
fig = go.Figure(data=[go.Pie(
labels=attr_by_dept['Department'],
values=attr_by_dept['Count'],
hole=0.4,
marker=dict(colors=['red', 'green']),
textposition='inside'

)])

# Update the Layout
fig.update_layout(title='Attrition by Department')

# Show the chart
fig.show()

In [126]:
# Create a donut chart
fig = go.Figure(data=[go.Pie(
labels=attr_by_yr['YearsAtCompany'],
values=attr_by_yr['Count'],
hole=0.4,
marker=dict(colors=['red', 'green']),
textposition='inside'

)])

# Update the Layout
fig.update_layout(title='Attrition by Department')

# Show the chart
fig.show()

We can see that the employees with Lite
Sciences as an education field have a high
attrition rate. Now let's have a look at the
percentage of attrition by number of years at the
company

In [127]:
# Create a donut chart
fig = go.Figure(data=[go.Pie(
labels=attr_by_yr['YearsAtCompany'],
values=attr_by_yr['Count'],
hole=0.4,
marker=dict(colors=['red', 'green']),
textposition='inside'

)])

# Update the Layout
fig.update_layout(title='Attrition by Years at Company')

# Show the chart
fig.show()

In [131]:
# We can see that the employees who don't get
# promotions leave the organization more
# compared to the employees who got promotions.
# Now let's have a look at the percentage of
# attrition by gender:

In [132]:
attrition_by = attr_df. groupby([ 'Gender' ]) .size().reset_index(name='count')
attrition_by
# Create a donut chart
fig = go.Figure(data=[go.Pie(
labels=attrition_by['Gender'],
values=attrition_by['count'],


marker=dict(colors=['#3CAEA3', '#F6D55C']),
textposition='inside'
)])
# Update the Layout
fig.update_layout(title='Attrition by Gender')
# Show the chart
fig.show()

In [138]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from statsmodels) (2.4.6)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from statsmodels) (3.0.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\piyush\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB 165.2 kB/s eta 0:00:58
   ---------------------------------------- 0.0/9.6 MB 245.8 kB/s eta 0:00:39
   -- ------------------------------------- 0.5/9.6 MB 2.7 MB/s eta 0:00:04
   --- ------------------------------------ 0.8/9.6 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/9.6 MB 3.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.6 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.0/9.6 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.1/9.6 MB 2.6 MB/s eta 0:00:04
   ------ --------------------------------- 1.7/9.6 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.6 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.0/9.6 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.2/9.6 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.2/9.6 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.2/9.6 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.4/9.6 MB 3.3 MB/s eta 0:00:03
   ----------- ---------------------------- 2.6/9.6 MB 3.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.6 MB 3.7 MB/s eta 0:00:02
   ------------- -------------------------- 3.3/9.6 MB 3.7 MB/s eta 0:00:02
   -------------- ------------------------- 3.5/9.6 MB 3.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.6/9.6 MB 3.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.8/9.6 MB 3.8 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/9.6 MB 3.8 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.6 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 4.4/9.6 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.6 MB 3.8 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.6 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 4.9/9.6 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.1/9.6 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/9.6 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 5.4/9.6 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 5.6/9.6 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.1/9.6 MB 3.8 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.6 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 6.5/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 6.7/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 6.9/9.6 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.2/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.4/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.6 MB 3.8 MB/s eta 0:00:01
   -------------------------------- ------- 7.8/9.6 MB 3.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.0/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.2/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.3/9.6 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.5/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.6 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.1/9.6 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  9.6/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 3.8 MB/s eta 0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
   ---------------------------------------- 0.0/233.3 kB ? eta -:--:--
   -------------------------------------- - 225.3/233.3 kB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 233.3/233.3 kB 2.9 MB/s eta 0:00:00
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.2 statsmodels-0.14.6

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [139]:
import plotly.express as px

fig = px.scatter(
    df,
    x="Age",
    y="MonthlyIncome",
    color="Attrition",
    trendline="ols"
)

fig.update_layout(
    title="Age vs Monthly Income by Attrition",
    xaxis_title="Age",
    yaxis_title="Monthly Income"
)

fig.show()

In [66]:
categorical_Col = df.select_dtypes(include='object').columns
cat = categorical_Col
numerical_Col = df.select_dtypes(exclude='object').columns
num = numerical_Col

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_30652\1317753785.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_Col = df.select_dtypes(include='object').columns

In [67]:
categorical = df[categorical_Col]

In [68]:
categorical.head()

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
0,Yes,Travel_Rarely,Sales,Life Sciences,Female,Sales Executive,Single,Y,Yes
1,No,Travel_Frequently,Research & Development,Life Sciences,Male,Research Scientist,Married,Y,No
2,Yes,Travel_Rarely,Research & Development,Other,Male,Laboratory Technician,Single,Y,Yes
3,No,Travel_Frequently,Research & Development,Life Sciences,Female,Research Scientist,Married,Y,Yes
4,No,Travel_Rarely,Research & Development,Medical,Male,Laboratory Technician,Married,Y,No

In [69]:
categorical['Attrition'] = categorical['Attrition'].map({'Yes': 1, 'No': 0})
categorical['OverTime'] = categorical['OverTime'].map({'Yes': 1, 'No': 0})
categorical['BusinessTravel'] = categorical['BusinessTravel'].map({'Non-Travel': 0, 'Travel_Rarely': 1, 'Travel_Frequently': 2})
categorical['Department'] = categorical['Department'].map({'Sales': 0, 'Research & Development': 1, 'Human Resources': 2})
categorical['EducationField'] = categorical['EducationField'].map({'Life Sciences': 0, 'Medical': 1, 'Marketing': 2, 'Technical Degree': 3, 'Human Resources': 4, 'Other': 5})
categorical['Gender'] = categorical['Gender'].map({'Male': 0, 'Female': 1})
categorical['JobRole'] = categorical['JobRole'].map({'Sales Executive': 0, 'Research Scientist': 1, 'Laboratory Technician': 2, 'Manufacturing Director': 3, 'Healthcare Representative': 4, 'Manager': 5, 'Sales Representative': 6, 'Research Director': 7, 'Human Resources': 8})    
categorical['MaritalStatus'] = categorical['MaritalStatus'].map({'Single': 0, 'Married': 1, 'Divorced': 2})
categorical['Over18'] = categorical['Over18'].map({'Y': 1, 'N': 0})

In [70]:
numerical = df[numerical_Col]
numerical.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2

In [71]:
numerical = numerical.rename(columns={'EmployeeNumber': 'Employee_Number', 'StandardHours': 'Standard_Hours', 'EmployeeCount': 'Employee_Count', 'DailyRate': 'Daily_Rate', 'HourlyRate': 'Hourly_Rate', 'MonthlyRate': 'Monthly_Rate'})

In [72]:
numerical

,Age,Daily_Rate,DistanceFromHome,Education,Employee_Count,Employee_Number,EnvironmentSatisfaction,Hourly_Rate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,Standard_Hours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,3,80,1,17,3,3,5,2,0,3
1466,39,613,6,1,1,2062,4,42,2,3,...,1,80,1,9,5,3,7,7,1,7
1467,27,155,4,3,1,2064,2,87,4,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,1023,2,3,1,2065,4,63,2,2,...,4,80,0,17,3,2,9,6,0,8
1469,34,628,8,3,1,2068,2,82,4,2,...,1,80,0,6,3,4,4,3,1,2

In [73]:
new_df = pd.concat([categorical, numerical], axis=1)
new_df.head()

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime,Age,...,RelationshipSatisfaction,Standard_Hours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,1,0,0,1,0,0,1,1,41,...,1,80,0,8,0,1,6,4,0,5
1,0,2,1,0,0,1,1,1,0,49,...,4,80,1,10,3,3,10,7,1,7
2,1,1,1,5,0,2,0,1,1,37,...,2,80,0,7,3,3,0,0,0,0
3,0,2,1,0,1,1,1,1,1,33,...,3,80,0,8,3,3,8,7,3,0
4,0,1,1,1,0,2,1,1,0,27,...,4,80,1,6,3,3,2,2,2,2

In [74]:
new_df.loc[15:26,list(cat)]

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
15,0,1,1,0,1,3,2,1,0
16,0,1,1,0,0,1,2,1,1
17,0,0,1,1,0,2,2,1,1
18,0,1,0,0,1,5,1,1,0
19,0,1,1,0,0,1,0,1,1
20,0,0,1,5,1,3,2,1,0
21,1,1,0,0,0,6,0,1,0
22,0,1,1,0,1,7,0,1,0
23,0,1,1,0,0,1,0,1,0
24,1,1,1,1,0,1,0,1,0
25,0,1,1,5,1,5,2,1,0
26,1,2,1,0,1,1,0,1,1

In [81]:
num = new_df.select_dtypes(include='number').columns

new_df[num].describe()

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime,Age,...,RelationshipSatisfaction,Standard_Hours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,0.161224,1.086395,0.739456,1.153741,0.400000,2.553061,0.902721,1.0,0.282993,36.923810,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,0.367863,0.532170,0.527792,1.383865,0.490065,2.323902,0.730121,0.0,0.450606,9.135373,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,18.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.0,0.000000,30.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,0.000000,1.000000,1.000000,1.000000,0.000000,2.000000,1.000000,1.0,0.000000,36.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,0.000000,1.000000,1.000000,2.000000,1.000000,4.000000,1.000000,1.0,1.000000,43.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,1.000000,2.000000,2.000000,5.000000,1.000000,8.000000,2.000000,1.0,1.000000,60.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [84]:
x = categorical.to_csv('categorical.csv')

In [88]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   --- ----------------------------------- 20.5/250.9 kB 217.9 kB/s eta 0:00:02
   ------ -------------------------------- 41.0/250.9 kB 326.8 kB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 1.5 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [89]:
numerical.to_excel('numerical.xlsx', index=False)

In [93]:
numerical.sort_values(by='Daily_Rate', ascending=False).head(10)

,Age,Daily_Rate,DistanceFromHome,Education,Employee_Count,Employee_Number,EnvironmentSatisfaction,Hourly_Rate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,Standard_Hours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
427,60,1499,28,3,1,573,3,80,2,3,...,4,80,0,22,5,4,18,13,13,11
986,39,1498,21,4,1,1390,1,44,2,2,...,4,80,2,8,2,4,5,4,1,4
1056,28,1496,1,3,1,1486,1,92,3,1,...,4,80,1,5,3,4,3,2,1,2
155,29,1496,1,1,1,208,4,41,3,2,...,1,80,1,10,1,3,10,7,0,9
471,38,1495,10,3,1,634,3,76,3,2,...,3,80,1,18,4,3,1,0,0,0
1044,49,1495,5,4,1,1473,1,96,3,2,...,2,80,1,20,0,2,3,2,1,2
1202,38,1495,4,2,1,1687,4,87,3,1,...,4,80,1,7,5,2,0,0,0,0
785,40,1492,20,4,1,1092,1,61,3,3,...,4,80,1,14,6,3,11,10,11,1
1422,35,1490,11,4,1,2003,4,43,3,1,...,3,80,1,5,3,3,2,2,2,2
408,52,1490,4,2,1,546,4,30,3,4,...,4,80,0,31,2,1,5,2,1,4